//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityFrameworkAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert query to enumerable.
        /// </summary>
        internal static string ConstructorCallQueryableCodeFixTitle {
            get {
                return ResourceManager.GetString("ConstructorCallQueryableCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling class constructor on Queryable will throw an exception because it cannot be translated to sql statement.
        /// </summary>
        internal static string ConstructorCallQueryableDescription {
            get {
                return ResourceManager.GetString("ConstructorCallQueryableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling class constructor on Queryable will throw an exception.
        /// </summary>
        internal static string ConstructorCallQueryableMessageFormat {
            get {
                return ResourceManager.GetString("ConstructorCallQueryableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling class constructor on Queryable will throw an exception.
        /// </summary>
        internal static string ConstructorCallQueryableTitle {
            get {
                return ResourceManager.GetString("ConstructorCallQueryableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Include method with lambda expression overload. This provides compile time validation and refactoring support.
        /// </summary>
        internal static string IncludeLambdaAnalyzerDescription {
            get {
                return ResourceManager.GetString("IncludeLambdaAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Include method with lambda expression overload instead of passing &apos;{0}&apos; as string.
        /// </summary>
        internal static string IncludeLambdaAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("IncludeLambdaAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Include method with lambda expression overload instead of string path.
        /// </summary>
        internal static string IncludeLambdaAnalyzerTitle {
            get {
                return ResourceManager.GetString("IncludeLambdaAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Include with overload that takes a lambda expression.
        /// </summary>
        internal static string IncludeLambdaCodeFixTitle {
            get {
                return ResourceManager.GetString("IncludeLambdaCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to overload that takes lambda expression as a parameter.
        /// </summary>
        internal static string UsePaginationLambdaOverloadCodeFixTitle {
            get {
                return ResourceManager.GetString("UsePaginationLambdaOverloadCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using overload which takes lambda expression will generate parameterized sql statement. Query plan for the statement can be reused for different values.
        /// </summary>
        internal static string UsePaginationLambdaOverloadDescription {
            get {
                return ResourceManager.GetString("UsePaginationLambdaOverloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use overload which takes lambda to get parameterized query when calling {0}.
        /// </summary>
        internal static string UsePaginationLambdaOverloadMessageFormat {
            get {
                return ResourceManager.GetString("UsePaginationLambdaOverloadMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use overload which takes lambda expression.
        /// </summary>
        internal static string UsePaginationLambdaOverloadTitle {
            get {
                return ResourceManager.GetString("UsePaginationLambdaOverloadTitle", resourceCulture);
            }
        }
    }
}
